#!/usr/bin/env python3
"""Generate the AGENTS.md and README.md files Portolan requires per object.

PTL-FIL-001 wants both next to every catalog and collection; PTL-FIL-002 and
PTL-FIL-003 want the links that reach them.

Content is derived from the object's own metadata -- title, description,
assets, children -- so it cannot drift from what it documents.

Ownership is by marker: a file is only (re)written when it is missing or
carries this generator's "generated by" line. The rich agent guides ported
from the retired llms.txt files, and the vro/brp guides written by
make_vro_agents.py and generate_year_docs.py, carry no marker and are left
alone. READMEs follow the core.md floor: title, description, license,
provenance.

Usage:
  python3 tools/catalog/make_docs_files.py            # dry run
  python3 tools/catalog/make_docs_files.py --confirm
"""
from __future__ import annotations
import argparse
import json
import os
import sys
from pathlib import Path

sys.path.insert(0, str(Path(__file__).resolve().parents[2]))
from tools.lib.docs import linkify_orgs

ROOT = Path(__file__).resolve().parents[2]
CATALOG = Path(os.environ.get("PORTOLAN_NL_CATALOG", ROOT / "catalog"))

DATA_BASE = "https://data.source.coop/cholmes/portolan-nl"

GENERATED_BY = ("This file is generated by `tools/catalog/make_docs_files.py` from "
                "`{src}`. Edit the metadata, not this file.")
MARKER = "generated by `tools/catalog/make_docs_files.py`"


def _owned(path: Path) -> bool:
    """True when this generator may (re)write the file.

    Hand-maintained agent guides (ported from the retired llms.txt) and the
    vro/brp guides written by other generators carry no marker, so they are
    never overwritten here.
    """
    return not path.is_file() or MARKER in path.read_text()


def objects():
    """Every catalog.json and collection.json under catalog/."""
    for p in sorted(CATALOG.rglob("*.json")):
        if p.name not in ("catalog.json", "collection.json"):
            continue
        if ".portolan" in p.parts or "styles" in p.parts:
            continue
        yield p


def _first_para(doc: dict) -> str:
    return (doc.get("description") or "").split("\n\n")[0].strip()


def _children(doc: dict) -> tuple[int, int]:
    links = doc.get("links") or []
    kids = sum(1 for l in links if isinstance(l, dict) and l.get("rel") == "child")
    items = sum(1 for l in links if isinstance(l, dict) and l.get("rel") == "item")
    return kids, items


def render_agents(doc: dict, path: Path) -> str:
    rel = path.parent.relative_to(CATALOG).as_posix() or "."
    title = doc.get("title") or doc.get("id") or rel
    kind = "collection" if doc.get("type") == "Collection" else "catalog"
    out = [f"# {title}", "", f"Portolan {kind} — `{rel}`", ""]

    para = _first_para(doc)
    if para:
        out += [linkify_orgs(para), ""]

    assets = doc.get("assets") or {}
    if assets:
        out += ["## Assets", "", "| Key | File | Type | Roles |", "|---|---|---|---|"]
        base = f"{DATA_BASE}/{rel}" if rel != "." else DATA_BASE
        for k, a in assets.items():
            if not isinstance(a, dict):
                continue
            href = str(a.get("href", ""))
            # Relative hrefs link to the published object -- the data files are
            # deliberately absent from the repo, so only absolute URLs resolve
            # everywhere the page is read.
            if href.startswith("http"):
                cell = f"[`{href}`]({href})"
            elif href:
                cell = f"[`{href}`]({base}/{href.lstrip('./')})"
            else:
                cell = ""
            out.append(f"| `{k}` | {cell} | {a.get('type', '')} | "
                       f"{', '.join(a.get('roles') or [])} |")
        out.append("")

    kids, items = _children(doc)
    if kids or items:
        out += ["## Contains", ""]
        if kids:
            out.append(f"- {kids} child catalog(s) or collection(s)")
        if items:
            out.append(f"- {items} item(s)")
        out += ["", f"See the links in [`{path.name}`](./{path.name}).", ""]

    out += ["## Access", "",
            "All assets are public. Relative hrefs resolve against this "
            "directory on <https://data.source.coop/cholmes/portolan-nl/>.", "",
            "---", "", GENERATED_BY.format(src=path.name), ""]
    return "\n".join(out)


def _inherited(doc: dict, path: Path, key: str):
    """A field from the object or its nearest ancestor that carries it.

    The kb subcatalogs declare no license or providers of their own; those
    live on the collection above them, and the spec's README floor (title,
    description, license, provenance) applies to every object.
    """
    if doc.get(key):
        return doc[key]
    for parent in path.parent.parents:
        for name in ("collection.json", "catalog.json"):
            f = parent / name
            if f.is_file():
                d = json.loads(f.read_text())
                if d.get(key):
                    return d[key]
                break
        if parent == CATALOG:
            break
    return None


def render_readme(doc: dict, path: Path) -> str:
    """A README for objects that have none. Deliberately short.

    Carries the core.md floor: title, description, license, provenance.
    """
    rel = path.parent.relative_to(CATALOG).as_posix() or "."
    title = doc.get("title") or doc.get("id") or rel
    out = [f"# {title}", ""]

    para = _first_para(doc)
    if para:
        out += [linkify_orgs(para), ""]

    out += ["> Agents: the machine-oriented guide for this data is "
            "[`AGENTS.md`](./AGENTS.md).", ""]

    bbox = ((doc.get("extent") or {}).get("spatial") or {}).get("bbox")
    interval = ((doc.get("extent") or {}).get("temporal") or {}).get("interval")
    if bbox or interval:
        out += ["## Extent", ""]
        if bbox:
            b = bbox[0]
            out.append(f"- **Bounding box** (WGS84): {b[0]}, {b[1]} → {b[2]}, {b[3]}")
        if interval and interval[0][0]:
            out.append(f"- **Time**: {interval[0][0]} → {interval[0][1]}")
        out.append("")

    kids, items = _children(doc)
    if items:
        out += ["## Contents", "",
                f"{items} STAC items, each a Cloud-Optimized GeoTIFF tile with a "
                f"WebP thumbnail. Open [`{path.name}`](./{path.name}) to enumerate them.", ""]
    elif kids:
        out += ["## Contents", "",
                f"{kids} child object(s). See [`{path.name}`](./{path.name}).", ""]

    out += ["## Use", "",
            "```bash",
            f"curl -s https://data.source.coop/cholmes/portolan-nl/{rel}/{path.name} | jq .",
            "```", ""]

    lic = _inherited(doc, path, "license")
    if lic:
        out += ["## License", "", f"`{lic}` — see the object metadata for any per-asset terms.", ""]

    provs = _inherited(doc, path, "providers")
    if provs:
        parts = []
        for pr in provs:
            if not isinstance(pr, dict):
                continue
            name = pr.get("name", "")
            roles = ", ".join(pr.get("roles") or [])
            url = pr.get("url")
            parts.append(f"[{name}]({url}) ({roles})" if url else f"{name} ({roles})")
        if parts:
            out += ["## Provenance", "", "Produced and served by " + "; ".join(parts) + ".", ""]

    out += ["---", "", GENERATED_BY.format(src=path.name), ""]
    return "\n".join(out)


def main(argv=None) -> int:
    ap = argparse.ArgumentParser(description=__doc__,
                                 formatter_class=argparse.RawDescriptionHelpFormatter)
    ap.add_argument("--confirm", action="store_true")
    args = ap.parse_args(argv)

    wrote_a = wrote_r = 0
    for p in objects():
        doc = json.loads(p.read_text())

        agents = p.parent / "AGENTS.md"
        if _owned(agents):
            text = render_agents(doc, p)
            if not agents.is_file() or agents.read_text() != text:
                wrote_a += 1
                if args.confirm:
                    agents.write_text(text)

        readme = p.parent / "README.md"
        if _owned(readme):              # hand-written READMEs are never touched
            text = render_readme(doc, p)
            if not readme.is_file() or readme.read_text() != text:
                wrote_r += 1
                if args.confirm:
                    readme.write_text(text)

    verb = "wrote" if args.confirm else "would write"
    print(f"{verb} {wrote_a} AGENTS.md and {wrote_r} README.md file(s)")
    if not args.confirm:
        print("Re-run with --confirm to write.")
    return 0


if __name__ == "__main__":
    sys.exit(main())
