#!/usr/bin/env python3
"""Generate the AGENTS.md and README.md files Portolan requires per object.

PTL-FIL-001 wants both next to every catalog and collection; PTL-FIL-002 and
PTL-FIL-003 want the links that reach them.

Content is derived from the object's own metadata -- title, description,
assets, children -- so it cannot drift from what it documents. Where a
hand-written llms.txt already exists, AGENTS.md points at it rather than
restating the query examples: sixty files of generic filler would help nobody.

Only writes what is missing. Hand-written READMEs are never overwritten;
AGENTS.md is generated, so it is rewritten whenever the metadata changes.

Usage:
  python3 tools/catalog/make_docs_files.py            # dry run
  python3 tools/catalog/make_docs_files.py --confirm
"""
from __future__ import annotations
import argparse
import json
import os
import sys
from pathlib import Path

ROOT = Path(__file__).resolve().parents[2]
CATALOG = Path(os.environ.get("PORTOLAN_NL_CATALOG", ROOT / "catalog"))

GENERATED_BY = ("This file is generated by `tools/catalog/make_docs_files.py` from "
                "`{src}`. Edit the metadata, not this file.")


def objects():
    """Every catalog.json and collection.json under catalog/."""
    for p in sorted(CATALOG.rglob("*.json")):
        if p.name not in ("catalog.json", "collection.json"):
            continue
        if ".portolan" in p.parts or "styles" in p.parts:
            continue
        yield p


def _first_para(doc: dict) -> str:
    return (doc.get("description") or "").split("\n\n")[0].strip()


def _children(doc: dict) -> tuple[int, int]:
    links = doc.get("links") or []
    kids = sum(1 for l in links if isinstance(l, dict) and l.get("rel") == "child")
    items = sum(1 for l in links if isinstance(l, dict) and l.get("rel") == "item")
    return kids, items


def render_agents(doc: dict, path: Path) -> str:
    rel = path.parent.relative_to(CATALOG).as_posix() or "."
    title = doc.get("title") or doc.get("id") or rel
    kind = "collection" if doc.get("type") == "Collection" else "catalog"
    out = [f"# {title}", "", f"Portolan {kind} — `{rel}`", ""]

    para = _first_para(doc)
    if para:
        out += [para, ""]

    if (path.parent / "llms.txt").is_file():
        out += ["## Start here", "",
                "Field descriptions, query examples and caveats are in "
                "[`llms.txt`](./llms.txt). It is hand-written and more useful "
                "than anything this file would repeat.", ""]

    assets = doc.get("assets") or {}
    if assets:
        out += ["## Assets", "", "| Key | File | Type | Roles |", "|---|---|---|---|"]
        for k, a in assets.items():
            if not isinstance(a, dict):
                continue
            out.append(f"| `{k}` | `{a.get('href', '')}` | {a.get('type', '')} | "
                       f"{', '.join(a.get('roles') or [])} |")
        out.append("")

    kids, items = _children(doc)
    if kids or items:
        out += ["## Contains", ""]
        if kids:
            out.append(f"- {kids} child catalog(s) or collection(s)")
        if items:
            out.append(f"- {items} item(s)")
        out += ["", f"See the links in [`{path.name}`](./{path.name}).", ""]

    out += ["## Access", "",
            "All assets are public. Relative hrefs resolve against this "
            "directory on <https://data.source.coop/cholmes/portolan-nl/>.", "",
            "---", "", GENERATED_BY.format(src=path.name), ""]
    return "\n".join(out)


def render_readme(doc: dict, path: Path) -> str:
    """A README for objects that have none. Deliberately short."""
    rel = path.parent.relative_to(CATALOG).as_posix() or "."
    title = doc.get("title") or doc.get("id") or rel
    out = [f"# {title}", ""]

    para = _first_para(doc)
    if para:
        out += [para, ""]

    bbox = ((doc.get("extent") or {}).get("spatial") or {}).get("bbox")
    interval = ((doc.get("extent") or {}).get("temporal") or {}).get("interval")
    if bbox or interval:
        out += ["## Extent", ""]
        if bbox:
            b = bbox[0]
            out.append(f"- **Bounding box** (WGS84): {b[0]}, {b[1]} → {b[2]}, {b[3]}")
        if interval and interval[0][0]:
            out.append(f"- **Time**: {interval[0][0]} → {interval[0][1]}")
        out.append("")

    kids, items = _children(doc)
    if items:
        out += ["## Contents", "",
                f"{items} STAC items, each a Cloud-Optimized GeoTIFF tile with a "
                f"WebP thumbnail. Open [`{path.name}`](./{path.name}) to enumerate them.", ""]
    elif kids:
        out += ["## Contents", "",
                f"{kids} child object(s). See [`{path.name}`](./{path.name}).", ""]

    out += ["## Use", "",
            "```bash",
            f"curl -s https://data.source.coop/cholmes/portolan-nl/{rel}/{path.name} | jq .",
            "```", "",
            "See [`AGENTS.md`](./AGENTS.md) for the machine-readable summary.", "",
            "---", "", GENERATED_BY.format(src=path.name), ""]
    return "\n".join(out)


def main(argv=None) -> int:
    ap = argparse.ArgumentParser(description=__doc__,
                                 formatter_class=argparse.RawDescriptionHelpFormatter)
    ap.add_argument("--confirm", action="store_true")
    args = ap.parse_args(argv)

    wrote_a = wrote_r = 0
    for p in objects():
        doc = json.loads(p.read_text())

        agents = p.parent / "AGENTS.md"
        text = render_agents(doc, p)
        if not agents.is_file() or agents.read_text() != text:
            wrote_a += 1
            if args.confirm:
                agents.write_text(text)

        readme = p.parent / "README.md"
        if not readme.is_file():        # never overwrite a hand-written README
            wrote_r += 1
            if args.confirm:
                readme.write_text(render_readme(doc, p))

    verb = "wrote" if args.confirm else "would write"
    print(f"{verb} {wrote_a} AGENTS.md and {wrote_r} README.md file(s)")
    if not args.confirm:
        print("Re-run with --confirm to write.")
    return 0


if __name__ == "__main__":
    sys.exit(main())
